# Generated by Django 3.2.4 on 2021-06-09 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatre',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название театра'),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='place',
            field=models.CharField(max_length=20, verbose_name='Местоположение театра'),
        ),
    ]
