# Generated by Django 3.2.4 on 2021-06-09 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210609_0510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theatre',
            options={'verbose_name': 'Театр', 'verbose_name_plural': 'Театр'},
        ),
    ]
