# Generated by Django 3.2.4 on 2021-06-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_theatre_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятие'},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'verbose_name': 'Посетитель', 'verbose_name_plural': 'Посетитель'},
        ),
        migrations.AlterField(
            model_name='show',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название мероприятия'),
        ),
        migrations.AlterField(
            model_name='show',
            name='theatre',
            field=models.CharField(max_length=20, verbose_name='В каком театре проводится'),
        ),
        migrations.AlterField(
            model_name='show',
            name='visitors',
            field=models.IntegerField(verbose_name='Количество посетителей'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Ф.И.О'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='show',
            field=models.CharField(max_length=20, verbose_name='Какое мероприятие посещал(а)'),
        ),
    ]
