# Generated by Django 3.2.4 on 2021-06-09 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210609_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='theatre',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='main_app.theatre', verbose_name='В каком театре проводится'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='show',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='main_app.show', verbose_name='Какое мероприятие посещал(а)'),
        ),
    ]
